pipeline {
    agent any
    stages {
        stage("get ubication") {
            steps {
                bat 'cd demo'
            }
        }
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }
        stage('Finish') {
            steps {
                bat 'mvn --version'
            }
        }
    }
}