pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'cd demo && mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'cd demo && mvn test'
            }
        }
        stage('Finish') {
            steps {
                bat 'de demo && mvn --version'
            }
        }
    }
}