pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                // bat 'cd demo && mvn -B -DskipTests clean package'
                sh 'mvn -B -DskipTests clean package'
            }
            post {
                failure {
                   echo 'This will run only if failed'
                   sh 'ls'
                }
            }
        }
        stage('Test') {
            steps {
                // bat 'cd demo && mvn test'
                sh 'mvn test'
            }
        }
        stage('Finish') {
            steps {
                echo 'Finish revision'
            }
        }
    }
}